// pages/index.vue
<script>
export default {
    setup() {
        useMeta({ // eslint-disable-line
            title: "TTU GDSC",
            meta: {
                hid: 'description',
                name: 'description',
                content: "Home of the Texas Tech Google Developer Student Club, one stop shop for all things club related"
            }
        })
    }
};
</script>

<template>
    <div>
        <NuxtWelcome />
    </div>
</template>

// pages/index.tsx
import Grid from "@mui/material/Grid";
import type { NextPage } from "next";
import Head from "next/head";

import Socials from "../components/home/Socials";
import Navbar from "../components/Navbar";
import Hero from "../components/home/Hero";
import Team from "../components/home/Team";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <>
      {/*Metadata on the page*/}
      <Head>
        <title>Home - TTU GDSC</title>
        <meta content="Landing page of the Texas Tech Google Developer Student Club" />
      </Head>
      {/*Center all of the following components*/}
      <Grid container direction="column">
        <Navbar />
        <Hero />
        <Socials />
        <Team />
        <Footer />
      </Grid>
    </>
  );
};
export default Home;
